#!/usr/bin/env python3
"""
deser_probe.py - Insecure deserialization detection + safe confirmation.

Identifies serialized blob formats (Java/PHP/.NET/Python/Node), runs
reflection and time-based probes, and can fire DNS-callback gadgets for
blind OOB confirmation (only against your own OOB endpoint).

Usage:
  python tools/deser_probe.py <url>
  python tools/deser_probe.py <url> --cookie CUSTOMER
  python tools/deser_probe.py <url> --param "file=phar://uploads/x.phar"
  python tools/deser_probe.py <url> --oob <callback-domain> --gadget dns
  python tools/deser_probe.py <url> --time 5

No RCE payloads are generated by this tool. Gadget callbacks are DNS-only.
"""

import argparse
import base64
import json
import re
import sys
import time
import urllib.parse

try:
    import requests
except ImportError:
    print("ERROR: requests not installed. Run: pip install requests")
    sys.exit(1)

TIMEOUT = 12
UA = "deser-probe/1.0"

MAGICS = [
    (r"^rO0AB", "JAVA", "Java serialization (ObjectInputStream)"),
    (r"^ACED0005", "JAVA", "Java serialization hex"),
    (r"^a:\d+:", "PHP", "PHP array serialization"),
    (r"^O:\d+:\"", "PHP", "PHP object serialization"),
    (r"^s:\d+:\"", "PHP", "PHP string serialization"),
    (r"^\x80\x04", "PYTHON", "Python pickle protocol 4"),
    (r"^gASV", "PYTHON", "Python pickle (base64)"),
    (r"^\{.+_\\$\\$ND_FUNC", "NODE", "node-serialize"),
    (r"^\/wEAA", ".NET", ".NET BinaryFormatter"),
    (r"^1\.2\.0\.0", ".NET", ".NET ViewState (v1.2)"),
    (r"^2\.2\.0\.0", ".NET", ".NET ViewState (v2.2)"),
    (r"^%[0-9a-fA-F]{2}", "URL", "URL-encoded (decode first)"),
]

MALFORMED_MARKERS = [
    (r"java\.io|ObjectInputStream|readObject|InvalidClassException", "JAVA"),
    (r"unserialize|__PHP_Incomplete_Class|Cannot access empty property", "PHP"),
    (r"pickle\.loads|UnpicklingError|_pickle", "PYTHON"),
    (r"ViewState|The state information is invalid|CryptographicException", ".NET"),
    (r"Serialize|deserialization", "GENERIC"),
]


def detect_format(raw: str):
    decoded = raw
    try:
        dec = base64.b64decode(raw + "==")
        decoded = dec.decode("latin-1", errors="replace")
    except Exception:
        pass
    for pat, kind, desc in MAGICS:
        if re.match(pat, decoded) or re.match(pat, raw):
            return kind, desc, decoded
    return None, None, decoded


def probe_cookie(sc, base, cookie_name, raw_value, oob=None, sleep=0):
    findings = []
    kind, desc, decoded = detect_format(raw_value)
    if kind:
        findings.append({"type": "serialized-blob", "cookie": cookie_name,
                         "format": kind, "desc": desc})
    # malformed reflection probe: corrupted but format-valid blob -> stack trace?
    if kind:
        malformed = raw_value + "AAAA"
        r = sc.get(base, cookies={cookie_name: malformed})
        if r is not None:
            for pat, m in MALFORMED_MARKERS:
                if re.search(pat, r.text[:2000], re.I):
                    findings.append({"type": "malformed-stack-trace", "cookie": cookie_name,
                                     "marker": m, "status": r.status_code})
                    break
    # time-based canary (only with --time)
    if sleep and kind:
        t0 = time.time()
        r = sc.get(base, cookies={cookie_name: raw_value})
        dt = time.time() - t0
        if r is not None and dt >= sleep - 0.5:
            findings.append({"type": "time-delay", "cookie": cookie_name,
                             "delay": round(dt, 2), "expected": sleep,
                             "note": "Response delayed ~= deserialization sink sleeping"})
    return findings


def probe_param(sc, base, param, value, oob=None, sleep=0):
    findings = []
    kind, desc, decoded = detect_format(value)
    if kind:
        findings.append({"type": "serialized-blob", "param": param, "format": kind, "desc": desc})
    if oob:
        # DNS-callback hint for phar:///URLDNS-style gadgets (only our own domain)
        callback = f"http://{oob}/{param.replace('.', '_')}/"
        q = urllib.parse.urlencode({param: value.replace("<OOB>", callback)})
        r = sc.get(f"{base}{'&' if '?' in base else '?'}{q}")
        if r is not None:
            findings.append({"type": "oob-fired", "param": param, "callback": callback,
                             "status": r.status_code,
                             "note": "Check oob_listener for inbound DNS/HTTP hit"})
    if sleep:
        t0 = time.time()
        r = sc.get(f"{base}{'&' if '?' in base else '?'}{urllib.parse.urlencode({param: value})}")
        dt = time.time() - t0
        if r is not None and dt >= sleep - 0.5:
            findings.append({"type": "time-delay", "param": param, "delay": round(dt, 2)})
    return findings


def main():
    ap = argparse.ArgumentParser(description="Insecure deserialization probe")
    ap.add_argument("url", nargs="?", default=None, help="target URL (required unless --value)")
    ap.add_argument("--cookie", help="cookie name to inspect/scan")
    ap.add_argument("--value", help="cookie/param raw value to analyze (offline)")
    ap.add_argument("--param", help="param to inject as name=value")
    ap.add_argument("--oob", help="your OOB callback domain (interactsh)")
    ap.add_argument("--time", type=int, default=0, help="sleep-canary seconds (safe time probe)")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    sc = requests.Session()
    sc.headers["User-Agent"] = UA
    findings = []

    if args.value:
        kind, desc, _ = detect_format(args.value)
        print(json.dumps({"blob": args.value[:120], "format": kind, "desc": desc}, indent=2))
        return

    if not args.url:
        print("ERROR: url required (or use --value for offline format detection)")
        sys.exit(1)

    if args.cookie:
        if args.oob or args.time:
            raw = args.value or "rO0AB"
        findings += probe_cookie(sc, args.url, args.cookie, raw, args.oob, args.time)
    if args.param:
        if "=" not in args.param:
            print("ERROR: --param needs name=value")
            sys.exit(1)
        name, val = args.param.split("=", 1)
        findings += probe_param(sc, args.url, name, val, args.oob, args.time)

    if args.json:
        print(json.dumps(findings, indent=2))
        return

    print(f"\n[+] Deserialization probe: {args.url}")
    if not findings:
        print("    No candidates. Try --cookie <name> on serialized-looking cookies, or --param.")
    for f in findings:
        print(f"  [!] {f['type']} {f.get('cookie') or f.get('param') or ''} "
              f"- {f.get('desc') or f.get('note') or ''} ({f.get('status','')})")
    print("\n[!] Confirm via OOB (--oob) or manual test; never fire RCE without human approval.")


if __name__ == "__main__":
    main()
